### ISSUE TITLE
Open Question: Is Model a place for parsing CSV files?

### ISSUE THREAD

**Issue by abhinavmsra** [m-rwash/google-scraping#2]
`Keyword` model has a class method `import` that performs csv file read and enqueues job in the background service. 

Does this function fit inside a Model, according to MVC principle?

**Comment by m-rwash** [comment]
Model should stick with business logic I know, but I was thinking of trying keeping model reusable I mean it takes a file, parse it and start processing. But that went away a little far from MVC standards, and model evolved into something else rather than just business logic.
You're right, parsing the CSV file should be in helper method. Sidekiq worker might fits well in our case.
