### ISSUE TITLE
Open Question: Any reason for still using include Sidekiq::Worker ??

### ISSUE THREAD

**Issue by abhinavmsra** [m-rwash/google-scraping#3]
In `ScrapeWorker `,

```
include Sidekiq::Worker
```

is used. 

Any reason for still using Sidekiq workers and can it done in some other ways?

**Comment by m-rwash** [comment]
I think you mean using ActiveJob instead, i think in our case it dosn't matter, but I always think of activejob as just a job queuer, unlike sidekiq which does queuing and processing, so I thought of using worker rather than a job. 
But of course it could be implemented by ActiveJob backed with sidekiq instead of what i did.
