### ISSUE TITLE
Setup of Testing Framework

### ISSUE THREAD

**Issue by abhinavmsra** [m-rwash/google-scraping#4]
1) Why is there both `Minitest` and `Rspec`?

2) In `keyword_fabricator `, 

```
ads_top_urls             FFaker::Internet.http_url+" , "*5
  ads_bottom_urls          FFaker::Internet.http_url+" , "*5
  non_ads_urls             FFaker::Internet.http_url+" , "*10
```

is used. What is the reason for it? Couldnt it be just  `FFaker::Internet.http_url`?

3) Tests for `Keyword ` model does not cover all the methods.

**Comment by m-rwash** [comment]
1. `Minitest` comes default with rails setup. and I forgot remove it when i decided to go with `Rspec`.
I've to clean that up.
2. Yes you'r absolutely right there's no need for that. Things got messed up, cause I was storing urls first as strings with comma delimiter before I changed database column type to arrays rather than strings
3. Yes I know, I was focusing more on the controller tests. The project is just 50% covered right now as `simplecov` states.
